name: GitHubAppreciator 

# Triggers 
on:
  # Triggers the workflow on a PR to the "main" or "master" branch is merged
  pull_request:
        types:
            - closed
        branches:
            - main
            - master
            
  # Triggers the workflow on calling from a different workflow
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a job to post Appreciation on Linkedin
  linkedinAppreciation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # trigger this job only if the pull request is merged and if it's not from the original user
    if: github.event.pull_request.merged == true
    # if: github.event.pull_request.merged == true && github.event.pull_request.user.login != 'prajwalraju'
        
    # Steps to collect all the info and send a post to Linkedin
    steps:
      - name: Install curl
        run : sudo apt-get install curl jq
      
      - run: echo ${{secrets.linkedinAuth}}
      - name: Get repo about
        run : |
          # Get repo details
          apiResponse=$(curl -L "https://api.github.com/repos/$GITHUB_REPOSITORY")

          #  Get repo description
          description=$(echo "$apiResponse" | jq -r '.description')
          echo "$description"
          
          # get repo tags
          topics_array=$(echo "$apiResponse" | jq -r '.topics[]')
          topics_string=$(echo "$topics_array" | sed 's/^/#/; s/$/ /' | tr -d '\n')

          # Get repos PR url 
          echo "GITHUB_EVENT_PATH : $GITHUB_EVENT_PATH"
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          PRURL="https://github.com/$GITHUB_REPOSITORY/pull/$pull_number"
          
          # make a post request to linkedin
          curl -L "https://api.linkedin.com/v2/ugcPosts" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{secrets.linkedinAuth}}" \
              -d "{
                  \"author\": \"urn:li:person:Pg-ex5GNjq\",
                  \"lifecycleState\": \"PUBLISHED\",
                  \"specificContent\": {
                      \"com.linkedin.ugc.ShareContent\": {
                          \"shareCommentary\": {
                              \"text\": \"🙌 A Big Thank You for Your Contribution! 🙌\n\nHey ${{ github.event.pull_request.user.login }},\n\nJust wanted to express my heartfelt thanks for your recent PR of $PRURL to our open source project $GITHUB_REPOSITORY. Your contribution is invaluable and greatly appreciated. It's folks like you who make our project thrive. Looking forward to more collaboration!\nPlease check out https://github.com/${{ github.event.pull_request.user.login }} for there work \n\nSome things about the project $GITHUB_REPOSITORY https://github.com/$GITHUB_REPOSITORY \n\n $description.\n\n #opensource $topics_string \"
                          },
                          \"shareMediaCategory\": \"NONE\"
                      }
                  },
                  \"visibility\": {
                      \"com.linkedin.ugc.MemberNetworkVisibility\": \"CONNECTIONS\"
                  }
              }" 
      
